Repository casper-network/docs, pull requests merged in 2023-03, with the labels that each got.

#885 861 Polishing Speculative Execution Documentation
  source/docs/casper/dapp-dev-guide/sdkspec/json-rpc-transactional.md
Labels: v1.5

#968 Polish Sending Deploys page
  source/docs/casper/developers/dapps/sending-deploys.md
Labels: TT modify content

#965 Improve AccountHash explanation
  source/docs/casper/developers/json-rpc/types_chain.md
  source/docs/casper/developers/json-rpc/types_cl.md
Labels: TT modify content

#961 Add "Deploy & the Deploy Lifecycle" concept
  config/sidebar.config.js
  source/docs/casper/concepts/deploy-and-deploy-lifecycle.md
  source/docs/casper/concepts/design/casper-design.md
Labels: TT new content

#980 Add "Global State" concept
  config/sidebar.config.js
  source/docs/casper/concepts/design/casper-design.md
  source/docs/casper/concepts/global-state.md
  source/docs/casper/concepts/index.md
  source/docs/casper/operators/setup-network/create-private.md
  source/docs/casper/resources/build-on-casper/casper-open-source-software.md
Labels: TT new content

#990 Add NavData plugin
  .env.example
  .github/workflows/main.yml
  README.md
  config/index.js
  config/site.navbar.config.js
  docusaurus.config.js
  package.json
  src/plugins/docusaurus-plugin-navdata/.github/workflows/main.yml
  src/plugins/docusaurus-plugin-navdata/.github/workflows/size.yml
  src/plugins/docusaurus-plugin-navdata/.gitignore
  src/plugins/docusaurus-plugin-navdata/README.md
  src/plugins/docusaurus-plugin-navdata/package.json
  src/plugins/docusaurus-plugin-navdata/src/convertData.ts
  src/plugins/docusaurus-plugin-navdata/src/index.ts
  src/plugins/docusaurus-plugin-navdata/src/interfaces/navbar/column.ts
  src/plugins/docusaurus-plugin-navdata/src/interfaces/navbar/footerColumn.ts
  src/plugins/docusaurus-plugin-navdata/src/interfaces/navbar/footerData.ts
  src/plugins/docusaurus-plugin-navdata/src/interfaces/navbar/group.ts
  src/plugins/docusaurus-plugin-navdata/src/interfaces/navbar/link.ts
  src/plugins/docusaurus-plugin-navdata/src/interfaces/navbar/navData.ts
  src/plugins/docusaurus-plugin-navdata/src/interfaces/navbar/navItem.ts
  src/plugins/docusaurus-plugin-navdata/src/interfaces/navbar/socialMedia.ts
  src/plugins/docusaurus-plugin-navdata/tsconfig.json
  src/plugins/docusaurus-plugin-navdata/yarn.lock
Labels: enhancement

#993 Configure CI/CD for new theme
  .github/templates/.env.production.j2
  .github/workflows/main.yml
  docusaurus.config.js
  package.json
  yarn.lock
Labels: enhancement

#966 Polished intro to SDKs
  source/docs/casper/developers/dapps/sdk/index.md
Labels: TT modify content

#997 Add basic unified SDK page
  config/sidebar.config.js
  source/docs/casper/developers/dapps/sdk/client-library-usage.md
Labels: TT new content
