Repository casper-network/docs, pull requests merged in 2023-06, with the labels that each got.

#1166 Cookie banner - navdata changes
  docusaurus.config.js
  src/plugins/docusaurus-plugin-navdata/src/convertData.ts
  src/plugins/docusaurus-plugin-navdata/src/index.ts
  src/plugins/docusaurus-plugin-navdata/src/interfaces/navbar/footerData.ts
Labels: enhancement

#1167 Cookie banner - plugin
  docusaurus.config.js
  package.json
  src/plugins/docusaurus-plugin-cookiesbanner/.github/workflows/main.yml
  src/plugins/docusaurus-plugin-cookiesbanner/.github/workflows/size.yml
  src/plugins/docusaurus-plugin-cookiesbanner/.gitignore
  src/plugins/docusaurus-plugin-cookiesbanner/README.md
  src/plugins/docusaurus-plugin-cookiesbanner/package.json
  src/plugins/docusaurus-plugin-cookiesbanner/src/convertData.ts
  src/plugins/docusaurus-plugin-cookiesbanner/src/index.ts
  src/plugins/docusaurus-plugin-cookiesbanner/src/interfaces/cookieData.ts
  src/plugins/docusaurus-plugin-cookiesbanner/src/interfaces/cookieItem.ts
  src/plugins/docusaurus-plugin-cookiesbanner/tsconfig.json
  src/plugins/docusaurus-plugin-cookiesbanner/yarn.lock
Labels: enhancement

#1168 Cookie banner - UI
  package.json
  src/hooks/useFocusTrap.ts
  src/icons/index.tsx
  src/theme/DocPage/Layout/index.jsx
  src/theme/DocPage/index.jsx
  src/theme/Footer/ExtendedFooter/ExtendedFooter.module.scss
  src/theme/Footer/ExtendedFooter/index.tsx
  src/theme/Modals/CookieModal/CookieModal.module.scss
  src/theme/Modals/CookieModal/index.tsx
  src/theme/Navbar/ExtendedNavbar/index.tsx
  yarn.lock
Labels: enhancement

#1058 Rewrote monitor & consume events
  source/docs/casper/developers/dapps/monitor-and-consume-events.md
Labels: TT modify content

#1053 Added calling contracts
  source/docs/casper/developers/dapps/sdk/client-library-usage.md
Labels: TT new content
